[CmdletBinding()]param([string]$ProjectRoot=".",[Parameter(Mandatory=$true)][string]$VerificationReceiptPath,[string]$AuditResultPath="",[switch]$Apply)
$ErrorActionPreference="Stop";$Root=(Resolve-Path $ProjectRoot).Path;$Agy=Join-Path $Root ".agy";$Wi=Get-Content (Join-Path $Agy "WORK_ITEM.json") -Raw|ConvertFrom-Json;$V=Get-Content (Resolve-Path $VerificationReceiptPath) -Raw|ConvertFrom-Json;$Findings=@();if(Test-Path (Join-Path $Agy "FINDINGS.json")){$Findings=@((Get-Content (Join-Path $Agy "FINDINGS.json") -Raw|ConvertFrom-Json).findings)};$Budget=$null;if(Test-Path (Join-Path $Agy "REPAIR_BUDGET.json")){$Budget=Get-Content (Join-Path $Agy "REPAIR_BUDGET.json") -Raw|ConvertFrom-Json};$Att=$null;if(Test-Path (Join-Path $Agy "REVIEWER_ATTESTATION.json")){$Att=Get-Content (Join-Path $Agy "REVIEWER_ATTESTATION.json") -Raw|ConvertFrom-Json};$Audit=$null;if($AuditResultPath){$Audit=Get-Content (Resolve-Path $AuditResultPath) -Raw|ConvertFrom-Json}
$Open=@($Findings|Where-Object{$_.lifecycle_status-eq"open_confirmed"});$Product=@($Open|Where-Object{$_.materiality-eq"product_blocker"});$Verify=@($Open|Where-Object{$_.materiality-eq"verification_blocker"});$Release=@($Open|Where-Object{$_.materiality-eq"release_blocker"});$Required=@($V.tests|Where-Object{$_.required-ne$false});$VerificationPassed=($Required.Count-gt0 -and @($Required|Where-Object{[int]$_.exit_code-ne0}).Count-eq0);$Independent=($Att -and $Att.independence_status-eq"independent");$AuditPassed=($Audit -and ($Audit.status-eq"passed" -or $Audit.audit_status-eq"passed") -and $Independent);$Mode=[string]$Wi.assurance_mode
if($Product.Count){$Acceptance="rejected";$Verification="failed";$AuditStatus=if($Mode-eq"flow"){"not_required"}else{"failed"};$Next=$false;$Reason="open_product_blocker"}
elseif(-not$VerificationPassed){$Acceptance="blocked";$Verification="blocked";$AuditStatus=if($Mode-eq"flow"){"not_required"}else{"blocked"};$Next=$false;$Reason="required_verification_missing_or_failed"}
elseif($Mode-ne"flow" -and -not$AuditPassed){$Acceptance="completed_with_verification_debt";$Verification="debt";$AuditStatus="unavailable";$Next=$true;$Reason="protected_audit_unavailable"}
elseif($Verify.Count -or $Release.Count){$Acceptance="completed_with_verification_debt";$Verification="debt";$AuditStatus=if($Mode-eq"flow"){"not_required"}else{"passed"};$Next=$true;$Reason="verification_or_release_debt"}
else{$Acceptance="accepted";$Verification="passed";$AuditStatus=if($Mode-eq"flow"){"not_required"}else{"passed"};$Next=$true;$Reason="all_material_gates_passed"}
$Branch=(& git -C $Root rev-parse --abbrev-ref HEAD).Trim();$Head=(& git -C $Root rev-parse HEAD).Trim();$Status=@(& git -C $Root status --porcelain);$Now=(Get-Date).ToUniversalTime().ToString("o");$Closure=[ordered]@{schema_version="1.0.0";work_item_id=[string]$Wi.work_item_id;implementation_status=if($Product.Count){"partial"}else{"completed"};verification_status=$Verification;audit_status=$AuditStatus;acceptance_status=$Acceptance;release_status=if($Acceptance-eq"accepted" -and $Mode-eq"release"){"open"}elseif($Mode-eq"release" -or $Acceptance-eq"completed_with_verification_debt"){"blocked"}else{"not_applicable"};next_owner_goal_allowed=$Next;closure_reason=$Reason;open_finding_ids=@($Open.finding_id);generated_at_utc=$Now}
$Run=[ordered]@{schema_version="1.0.0";work_item_id=[string]$Wi.work_item_id;assurance_mode=$Mode;branch=$Branch;head=$Head;git_state=if($Status.Count){"dirty"}else{"clean"};implementation_status=$Closure.implementation_status;verification_status=if($Verification-eq"debt"){"partial"}else{$Verification};audit_status=$AuditStatus;acceptance_status=$Acceptance;product_blockers=@($Product|%{[ordered]@{code=$_.finding_id.ToUpper().Replace('-','_');message=$_.title;category=$_.category;auto_repairable=[bool]$_.auto_repairable}});verification_blockers=@($Verify|%{[ordered]@{code=$_.finding_id.ToUpper().Replace('-','_');message=$_.title;category=$_.category;auto_repairable=[bool]$_.auto_repairable}});release_blockers=@($Release|%{[ordered]@{code=$_.finding_id.ToUpper().Replace('-','_');message=$_.title;category=$_.category;auto_repairable=[bool]$_.auto_repairable}});service_warnings=@();changed_files=@($V.changed_files);tests=@($V.tests);next_workflow=if($Product.Count){"/fixcritical"}elseif(-not$VerificationPassed){"/auditphase"}else{$null};no_progress=$false;hard_stop=(-not$Next);generated_at_utc=$Now;evidence_artifacts=@($V.evidence_artifacts);product_artifacts=@($V.product_artifacts);execution_lease_id=if(Test-Path (Join-Path $Agy "EXECUTION_LEASE.json")){[string](Get-Content (Join-Path $Agy "EXECUTION_LEASE.json") -Raw|ConvertFrom-Json).lease_id}else{$null};audit_coverage_status=if(Test-Path (Join-Path $Agy "AUDIT_COVERAGE_MATRIX.json")){[string](Get-Content (Join-Path $Agy "AUDIT_COVERAGE_MATRIX.json") -Raw|ConvertFrom-Json).status}else{"not_required"};reviewer_independence_status=if($Mode-eq"flow"){"not_required"}elseif($Att){[string]$Att.independence_status}else{"unavailable"};repair_batches_used=if($Budget){[int]$Budget.repair_batches_used}else{0};repair_batch_limit=if($Budget){[int]$Budget.repair_batch_limit}else{0};closure_state_path=".agy/CLOSURE_STATE.json"}
if($Apply){$U=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllText((Join-Path $Agy "CLOSURE_STATE.json"),($Closure|ConvertTo-Json -Depth 30),$U);[IO.File]::WriteAllText((Join-Path $Agy "RUN_RESULT.json"),($Run|ConvertTo-Json -Depth 40),$U);Write-Host "Compiled result authority: $Acceptance"}else{[ordered]@{closure=$Closure;run_result=$Run}|ConvertTo-Json -Depth 50}
