#!/usr/bin/env node
'use strict';
const fs=require('fs');const path=require('path');
const SCHEMA_VERSION='1.2.9';
const ECOSYSTEM_VERSION='1.2.18';
const ROUTES=new Set(['/nextphase','/fixcritical','/auditphase','/fastpatch','/shipcheck']);
function parseTime(v){const n=Date.parse(String(v||''));return Number.isFinite(n)?n:null;}
function validateOwnerSummary(text){const errors=[];for(const h of ['## Что происходит','## Что уже сделано','## Что будет дальше','## Нужно ли что-то от владельца'])if(!String(text||'').includes(h))errors.push(`OWNER_SUMMARY:${h}`);if(String(text||'').length>2400||String(text||'').includes('```'))errors.push('OWNER_SUMMARY_FORMAT');return errors;}
function validatePacketObject(packet,options={}){const errors=[];if(!packet||typeof packet!=='object'||Array.isArray(packet))return{ok:false,errors:['PACKET_OBJECT']};if(packet.schema_version!==SCHEMA_VERSION||packet.ecosystem_version!==ECOSYSTEM_VERSION)errors.push('VERSION');if(packet.packet_format!==undefined&&packet.packet_format!=='single_json')errors.push('FORMAT');if(!/^[A-Za-z0-9._-]{8,128}$/.test(String(packet.packet_id||'')))errors.push('PACKET_ID');if(!packet.project_id)errors.push('PROJECT_ID');if(options.requireCapability===true){if(!/^[0-9a-f]{64}$/.test(String(packet.capability_token||'')))errors.push('CAPABILITY_TOKEN');}else if(Object.prototype.hasOwnProperty.call(packet,'capability_token'))errors.push('EXTERNAL_CAPABILITY_FORBIDDEN');if(!['new_work_item','continue_work_item'].includes(packet.operation))errors.push('OPERATION');if(!ROUTES.has(packet.route))errors.push('ROUTE');if(packet.operation==='continue_work_item'&&(!packet.work_item_id||!Number.isInteger(packet.goal_epoch)))errors.push('CONTINUATION_IDENTITY');if(packet.owner_approved!==true)errors.push('OWNER_APPROVAL');if(packet.owner_interaction_policy!=='hard_stop_only')errors.push('OWNER_POLICY');if(!packet.goal)errors.push('GOAL');if(!String(packet.technical_task_markdown||'').trim())errors.push('TECHNICAL_TASK');errors.push(...validateOwnerSummary(packet.owner_summary_ru));const c=parseTime(packet.created_at_utc),e=parseTime(packet.expires_at_utc),now=options.nowMs??Date.now();if(c===null||e===null||e<=c)errors.push('PACKET_TIME_INVALID');if(e!==null&&now>e)errors.push('PACKET_EXPIRED');if(c!==null&&c>now+300000)errors.push('PACKET_FROM_FUTURE');return{ok:errors.length===0,errors,packet};}
function validatePacketPath(target,options={}){const stat=fs.statSync(target);if(stat.isFile()){if(path.extname(target).toLowerCase()!=='.json')return{ok:false,errors:['PACKET_EXTENSION']};let packet;try{packet=JSON.parse(fs.readFileSync(target,'utf8').replace(/^\uFEFF/,''));}catch(e){return{ok:false,errors:[`JSON:${e.message}`]}}return validatePacketObject(packet,options);}const file=path.join(target,'ACTION_PACKET.json');if(!fs.existsSync(file))return{ok:false,errors:['MISSING:ACTION_PACKET.json']};const packet=JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,''));if(fs.existsSync(path.join(target,'AGENT_TASK.md'))&&String(packet.technical_task_markdown||'').trimEnd()!==fs.readFileSync(path.join(target,'AGENT_TASK.md'),'utf8').trimEnd())return{ok:false,errors:['TASK_MATERIALIZATION_MISMATCH']};return validatePacketObject(packet,{...options,requireCapability:true});}
if(require.main===module){const target=process.argv[2];if(!target){console.error('Usage: action-packet.cjs <packet.json|materialized-directory>');process.exit(2)}const r=validatePacketPath(target);console.log(JSON.stringify(r,null,2));process.exitCode=r.ok?0:1;}
module.exports={validatePacketObject,validatePacketPath};
